### ISSUE TITLE
Correct typos, grammar and missing copy

### ISSUE THREAD

**Issue by SoMuchFreeTime** [danhollick/Not-Shite#5]
Skills section:
"especially, but not limited to, these things" - needs second comma after 'to'
"...at the best time-cost.." - needs an 'e' in 'time-cost'

process development:
"...easier to break in the right places." - missing the last part of the sentence

Writing:
"designing and writing go hand-in-hand. articulating ideas before and after design makes for critical thinking and deeper understanding of the product at every level." - new line

**Comment by enummela** [comment]
Proposed fix: #8.
